config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  get 'favorites/create'
  get 'favorites/destroy'

  devise_for :users
  resources :users, only: [:index, :show] do
    get 'favorite'
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end

  root "quotes#index"

  resources :quotes, only: [:index, :new, :create, :show] do
    collection do
      get 'search'
    end
    resource :favorites, only: [:create, :destroy]
    resource :comments, only: :create
  end

  resources :tags, only: :index
  get '/quote/tag/:name', to: "quotes#tag"
  get '/quote/tag' => 'quotes#tag'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :quote

  validates :text, length: { in: 1..280 }

  def created_at
    attributes['created_at'].strftime("%Y/%m/%d")
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :quote
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :user
  has_many :favorites
  has_many :comments
  has_many :quote_tags, dependent: :destroy
  has_many :tags, through: :quote_tags

  validates :title, :citation, :explanation, presence: true
  validates :title, length: { in: 1..100 }
  validates :citation, length: { in: 1..50 }
  validates :explanation, length: { in: 1..280 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  after_create do
    @quote = Quote.find_by(id: self.id)
    tags  = self.explanation.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    tags.uniq.map do |t|
      tag = Tag.find_or_create_by(name: t.downcase.delete('#'))
      @quote.tags << tag
    end
  end

  before_update do 
    @quote = Quote.find_by(id: self.id)
    @quote.hashtags.clear
    tags  = self.explanation.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    tags.uniq.map do |t|
      tag = Tag.find_or_create_by(name: t.downcase.delete('#'))
      @quote.tags << tag
    end
  end

  def self.search(keyword)
    Quote.where('(title LIKE?) OR (citation LIKE?) OR (explanation LIKE?)', "%#{keyword}}%", "%#{keyword}%", "%#{keyword}%")
  end

  def created_at
    attributes['created_at'].strftime("%Y/%m/%d")
  end
end

app/models/quote_tag.rb
class QuoteTag < ApplicationRecord
  belongs_to :quote
  belongs_to :tag
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :quote_tags, dependent: :destroy
  has_many :quotes, through: :quote_tags

  validates :name, presence: true, length: {maximum:20}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :quotes

  has_many :favorites
  has_many :favorite_quotes, through: :favorites, source: :quote

  has_many :comments

  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  validates :nickname, presence: true

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
 
  protected
 
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      respond_to do |format|
        format.json
      end
    else
      redirect_to quote_path(params[:quote_id])
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, quote_id: params[:quote_id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    favorite = current_user.favorites.build(quote_id: params[:quote_id])
    favorite.save
    redirect_to quotes_path
  end

  def destroy
    favorite = Favorite.find_by(quote_id: params[:quote_id], user_id: current_user.id)
    favorite.destroy
    redirect_to quotes_path
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController

  def index
    @quotes = Quote.includes(:comments).order('created_at DESC')
  end

  def new
    @quote = Quote.new
  end

  def create
    @quote = Quote.new(quote_params)
    if @quote.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @quote = Quote.find(params[:id])
    @comment = Comment.new
    @comments = Comment.includes(:user).where(quote_id: params[:id]).order("created_at DESC")
  end

  def tag
    @user = current_user
    if params[:name].nil?
      @tags = Tag.all.to_a.group_by{ |tag| tag.quotes.count}
    else
      @tag = Tag.find_by(name: params[:name])
      @quote = @tag.quotes.reverse_order
      @tags = Tag.all.to_a.group_by{ |tag| tag.quotes.count}
    end
   end

   def search
    @keyword = params[:keyword]
    @quotes = Quote.search(params[:keyword]).order("created_at DESC")
   end

  private
  def quote_params
    params.require(:quote).permit(:title, :citation, :explanation, :tag_ids).merge(user_id: current_user.id)
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    follow = current_user.active_relationships.build(follower_id: params[:user_id])
    follow.save
    redirect_to root_path
  end

  def destroy
    follow = current_user.active_relationships.find_by(follower_id: params[:user_id])
    follow.destroy
    redirect_to root_path
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end
  
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @quotes = user.quotes.order('created_at DESC')
  end

  def favorite
    @user = User.find(current_user.id)
    @quotes = @user.quotes
    @favorite_quotes = @user.favorite_quotes
  end

  def follows
    user = User.find(current_user.id)
    @users = user.followings
  end

  def followers
    user = User.find(current_user.id)
    @users = user.followers
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
  def render_with_tags(hashname)
    hashname.gsub(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/){|word| link_to word, "/quote/tag/#{word.delete("#")}"}.html_safe
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/quotes/index.html.haml
.Wrapper
  .container
    .QuoteCards
      - @quotes.each do |quote|
        = link_to new_quote_path, class: "badge badge-primary QuoteIcon" do
          .quote
            %i.fas.fa-quote-right
        = render partial: 'layouts/quotes-list', locals: { quote: quote}

app/views/quotes/new.html.haml
.Wrapper
  .container-login
    %h4 New Quote
    = form_with model: @quote do |f|
      .form-group
        = f.label :言葉
        = f.text_area :title, autofocus: true, autocomplete: 'title', class: 'form-control', required: true
      .form-group
        = f.label :発言者or出典
        = f.text_field :citation, autocomplete: 'current-citation', class: 'form-control', required: true
      .form-group
        = f.label :解説やハッシュタグ
        = f.text_area :explanation, autocomplete: 'current-explanation', class: 'form-control', required: true
      .space
      .form-group
        = f.submit 'POST', class: 'btn btn-primary btn-block'

app/views/quotes/search.html.haml
.Wrapper
  .container
    .SearchResults
      %h5
        = "「#{@keyword}」の検索結果"
      %h5
        = "ー#{@quotes.count}件"
    .QuoteCards
      - @quotes.each do |quote|
        = render partial: 'layouts/quotes-list', locals: { quote: quote}

app/views/quotes/show.html.haml
.Wrapper
  .container-login
    .QuoteCards
      = render partial: 'layouts/quotes-list', locals: { quote: @quote}
    %br/
    .CommentBox
      %h6 コメント
      .card.CommentIndex
        .card-body.comment-body
          - @comments.each do |comment|
            %p
              = comment.user.nickname
              = comment.created_at
            %p  
              = comment.text
      %br/
      .FormBox
        = form_with model: [@quote, @comment], id: "new_comment" do |f|
          .form-group
            = f.text_area :text, autofocus: true, autocomplete: 'title', class: 'form-control', required: true
            = f.submit '>', class: 'btn-primary CommentSubmitBtn'

app/views/quotes/tag.html.haml
.Wrapper
  .container
    - if params[:name] == nil
    - else
      %h6.tag-search-title
        =  "##{@tag.name} : #{@quote.count} 件"
      .QuoteCards
        - @quote.each do |quote|
          .BOX
            .block
              = quote.created_at
            .block
              = render partial: 'layouts/quotes-list', locals: { quote: quote}

app/views/tags/index.html.haml
.Wrapper
  .container
    - @tags.each do |tag|
      = link_to "/quote/tag/#{tag.name.delete("#")}" do
        = "##{tag.name}"

app/views/users/favorite.html.haml
.Wrapper
  .container
    %p.text-primary
      お気に入り一覧
    .QuoteCards
      - @favorite_quotes.each do |quote|
        = render partial: 'layouts/quotes-list', locals: { quote: quote}

app/views/users/followers.html.haml
.Wrapper
  .container-login
    %p.text-primary
      フォロワー 一覧
    - @users.each do |user|
      %hr/
      %p
        = link_to user.nickname, user_path(user.id)
        - if current_user != user
          = link_to user_relationships_path(user), method: :post, class: "quote" do
            %button.btn.btn-outline-primary.FollowBtn{:type => "button"} フォローする
        - else
          = link_to user_relationships_path(user), method: :delete, class: "quote" do
            %button.btn.btn-primary.FollowBtn{:type => "button"} フォロー中

app/views/users/follows.html.haml
.Wrapper
  .container-login
    %p.text-primary
      フォロー 一覧
    - @users.each do |user|
      %hr/
      %p
        = link_to user.nickname, user_path(user.id)
        - if current_user != user
          = link_to user_relationships_path(user), method: :delete, class: "quote" do
            %button.btn.btn-primary.FollowBtn{:type => "button"} フォロー中
        - else
          = link_to user_relationships_path(user), method: :post, class: "quote" do
            %button.btn.btn-outline-primary.FollowBtn{:type => "button"} フォローする

app/views/users/index.html.haml
.Wrapper
  .container-login
    %br/
    %p.text-primary
      = current_user.nickname
      さん
    %hr/
    .mypage-index
      %ul.MypageList
        %li.nav-item.active
          %i.fas.fa-heart
          %a.nav-link.mypage-link.inline{:href => user_favorite_path(current_user.id)} お気に入り
          = current_user.favorites.count
        %li.nav-item
          %i.fas.fa-check-square
          %a.nav-link.mypage-link.inline{:href => follows_user_path(current_user.id)} フォロー
          = current_user.followings.count
        %li.nav-item
          %i.fas.fa-check-circle
          %a.nav-link.mypage-link.inline{:href => followers_user_path(current_user.id)} フォロワー
          = current_user.followers.count
        %li.nav-item
          %i.fas.fa-quote-right
          %a.nav-link.mypage-link.inline{:href => user_path(current_user.id)} 投稿
          = current_user.quotes.count
      %hr/

app/views/users/show.html.haml
.Wrapper
  .container
    %p.text-primary
      = @nickname
      さんの投稿一覧
    .QuoteCards
      - @quotes.each do |quote|
        = render partial: 'layouts/quotes-list', locals: { quote: quote}