config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  get 'favorites/create'
  get 'favorites/destroy'

  devise_for :users
  resources :users, only: [:index, :show] do
    get 'favorite'
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end

  root "quotes#index"

  resources :quotes, only: [:index, :new, :create, :show] do
    collection do
      get 'search'
    end
    resource :favorites, only: [:create, :destroy]
    resource :comments, only: :create
  end

  resources :tags, only: :index
  get '/quote/tag/:name', to: "quotes#tag"
  get '/quote/tag' => 'quotes#tag'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :quote

  validates :text, length: { in: 1..280 }

  def created_at
    attributes['created_at'].strftime("%Y/%m/%d")
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :quote
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :user
  has_many :favorites
  has_many :comments
  has_many :quote_tags, dependent: :destroy
  has_many :tags, through: :quote_tags

  validates :title, :citation, :explanation, presence: true
  validates :title, length: { in: 1..100 }
  validates :citation, length: { in: 1..50 }
  validates :explanation, length: { in: 1..280 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  after_create do
    @quote = Quote.find_by(id: self.id)
    tags  = self.explanation.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    tags.uniq.map do |t|
      tag = Tag.find_or_create_by(name: t.downcase.delete('#'))
      @quote.tags << tag
    end
  end

  before_update do 
    @quote = Quote.find_by(id: self.id)
    @quote.hashtags.clear
    tags  = self.explanation.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    tags.uniq.map do |t|
      tag = Tag.find_or_create_by(name: t.downcase.delete('#'))
      @quote.tags << tag
    end
  end

  def self.search(keyword)
    Quote.where('(title LIKE?) OR (citation LIKE?) OR (explanation LIKE?)', "%#{keyword}}%", "%#{keyword}%", "%#{keyword}%")
  end

  def created_at
    attributes['created_at'].strftime("%Y/%m/%d")
  end
end

app/models/quote_tag.rb
class QuoteTag < ApplicationRecord
  belongs_to :quote
  belongs_to :tag
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :quote_tags, dependent: :destroy
  has_many :quotes, through: :quote_tags

  validates :name, presence: true, length: {maximum:20}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :quotes

  has_many :favorites
  has_many :favorite_quotes, through: :favorites, source: :quote

  has_many :comments

  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  validates :nickname, presence: true

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      respond_to do |format|
        format.json
      end
    else
      redirect_to quote_path(params[:quote_id])
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, quote_id: params[:quote_id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    favorite = current_user.favorites.build(quote_id: params[:quote_id])
    favorite.save
    redirect_to quotes_path
  end

  def destroy
    favorite = Favorite.find_by(quote_id: params[:quote_id], user_id: current_user.id)
    favorite.destroy
    redirect_to quotes_path
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController

  def index
    @quotes = Quote.includes(:comments).order('created_at DESC')
  end

  def new
    @quote = Quote.new
  end

  def create
    @quote = Quote.new(quote_params)
    if @quote.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @quote = Quote.find(params[:id])
    @comment = Comment.new
    @comments = Comment.includes(:user).where(quote_id: params[:id]).order("created_at DESC")
  end

  def tag
    @user = current_user
    if params[:name].nil?
      @tags = Tag.all.to_a.group_by{ |tag| tag.quotes.count}
    else
      @tag = Tag.find_by(name: params[:name])
      @quote = @tag.quotes.reverse_order
      @tags = Tag.all.to_a.group_by{ |tag| tag.quotes.count}
    end
   end

   def search
    @keyword = params[:keyword]
    @quotes = Quote.search(params[:keyword]).order("created_at DESC")
   end

  private
  def quote_params
    params.require(:quote).permit(:title, :citation, :explanation, :tag_ids).merge(user_id: current_user.id)
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end
  
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @quotes = user.quotes.order('created_at DESC')
  end

  def favorite
    @user = User.find(current_user.id)
    @quotes = @user.quotes
    @favorite_quotes = @user.favorite_quotes
  end

  def follows
    user = User.find(current_user.id)
    @users = user.followings
  end

  def followers
    user = User.find(current_user.id)
    @users = user.followers
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
  def render_with_tags(hashname)
    hashname.gsub(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/){|word| link_to word, "/quote/tag/#{word.delete("#")}"}.html_safe
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_comments.html.haml
- if user_signed_in?
  .comment-count
    %i.far.fa-comment-dots
    = quote.comments.ids.count

app/views/layouts/_favorite.html.haml
- if user_signed_in?
  .favorite-count
    - if quote.favorited_by?(current_user)
      = link_to quote_favorites_path(quote.id), method: :delete, class: "quote" do
        %i.fas.fa-heart
      = quote.favorites.count
    - else
      = link_to quote_favorites_path(quote.id), method: :post, class: "quote" do
        %i.far.fa-heart
      = quote.favorites.count

app/views/layouts/_follow.html.haml
- if user_signed_in? && current_user != quote.user
  - if quote.user.followed_by?(current_user)
    = link_to user_relationships_path(quote.user.id), method: :delete, class: "quote", data: { confirm: "#{quote.user.nickname}さんのフォローを解除" } do
      %button.btn.btn-primary.FollowBtn{:type => "button"} フォロー中
  - else
    = link_to user_relationships_path(quote.user.id), method: :post, class: "quote" do
      %button.btn.btn-outline-primary.FollowBtn{:type => "button"} フォローする

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  %a.navbar-brand{:href => root_path } QuoteTweet
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      - if user_signed_in?
        %li.nav-item.active
          %a.nav-link{:href => users_path}
            マイページ
            %span.sr-only (current)
        %li.nav-item
          %a.nav-link{ :href => tags_path } ハッシュタグ一覧
        %li.nav-item
          %a.nav-link{ :href => new_quote_path } 新規投稿
        %li.nav-item
          = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link"
      - else
        %li.nav-item.active
          %a.nav-link{:href => root_path }
            ゲストさん
            %span.sr-only (current)
        %li.nav-item
          %a.nav-link{:href => new_user_registration_path} 新規登録
        %li.nav-item
          %a.nav-link{:href => new_user_session_path} ログイン
    = form_with url: search_quotes_path, method: :get, local: true, class: "form-inline my-2 my-lg-0" do |f|
      = f.text_field :keyword, placeholder: "Search", class: "form-control mr-sm-2"
      %button.btn.btn-outline-success.my-2.my-sm-0{:type => "submit"} Search

app/views/layouts/_quotes-list.html.haml
= link_to quote_path(quote), class: "quote" do
  .card
    .card-header
      = quote.citation
    .card-body
      %h4.card-title
        = quote.title
      %p.card-text
        = render_with_tags(quote.explanation)
      %hr/
      %p.poster.inline2 投稿者:
      = link_to user_path(quote.user.id) do
        = quote.user.nickname
        = render partial: 'layouts/follow', locals: { quote: quote}
      %hr/
      .CountBox
        = render partial: 'layouts/comments', locals: { quote: quote}
        = render partial: 'layouts/favorite', locals: { quote: quote}

app/views/layouts/_tags.html.haml
= render_with_tags(@quotes.explanation)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width", :name => "viewport"}/
    %title QuoteTweet
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:crossorigin => "anonymous", :href => "https://use.fontawesome.com/releases/v5.14.0/css/all.css", :integrity => "sha384-HzLeBuhoNPvSl5KYnjx0BT+WB0QEEqLprO+NBkkk5gbc67FTaL7XIGa2w1L0Xbgc", :rel => "stylesheet"}/
    %link{:crossorigin => "anonymous", :href => "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css", :integrity => "sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO", :rel => "stylesheet"}/
    %script{:crossorigin => "anonymous", :integrity => "sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo", :src => "https://code.jquery.com/jquery-3.3.1.slim.min.js"}
    %script{:crossorigin => "anonymous", :integrity => "sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut", :src => "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"}
    %script{:crossorigin => "anonymous", :integrity => "sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k", :src => "https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"}
  %body
    = render 'layouts/header'
    = yield
    %nav.navbar.navbar-light.bg-light.footer
      %span.navbar-text
      %span.text-right.navbar-text copyright sd1104
          

app/views/shared/_flash_messages.html.haml
- flash.each do |msg_type, msg|
  #alert{:class => "alert alert-#{msg_type}", :role => "alert"}
    %a.close{"data-dismiss" => "alert", :href => "#"} ×
    = msg